---
title: "Mass Health"
type: "challenge"
description: "Import statistical data into a database and create SQL queries."
tags: "sql, postgres"
visibility: "onsite"
ignore:
- "mass-health.md"
- "mass-chip-data.csv"
